imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, build/*, database/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
        coverage:
            tests:
                override:
                    - command: "make phpunit"
                    - command: "php artisan migrate"
                      coverage:
                          file: "build/coverage.clover"
                          format: "php-clover"
